---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  type: NodePort
  ports:
    - port: 80
      name: http
      protocol: TCP
  selector:
    app: helloworld